micronaut:
  application:
    name: locationApi
datasources:
  default:
    url: jdbc:mysql://localhost:3306/restApi
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:
  default:
    allocator:
      max-order: 3
